@ospo:always-auth=true
@ospo:registry=https://ospo.pkgs.visualstudio.com/_packaging/PrivateNpm/npm/registry/

//ospo.pkgs.visualstudio.com/_packaging/PrivateNpm/npm/registry/:_authToken=${NPM_TOKEN}
//ospo.pkgs.visualstudio.com/_packaging/PrivateNpm/npm/:_authToken=${NPM_TOKEN}
